### ISSUE TITLE
Question: Why not use in production?

### ISSUE THREAD

**Issue by attzonko** [scubakiz/clusterinfo#1]
You mention not using in production environment. Why not? Can you please elaborate?

**Comment by scubakiz** [comment]
The design goal of the app from the start has been to function as a training aid, not as a replacement for Kubernetes Dashboard.  

So no provisions are made for production-level software, especially security, performance, support for mobile devices/smaller resolutions, etc.

There are liability issues involved with production apps that don't apply when something is training aids.  For example, what's to stop a use from changing the Cluster Info service into a LoadBalancer?  Then, the cluster is exposed to the outside with no security.  Without that disclaimer, I would be in court in a week.

Why not add security?  Have you ever configured the Kubernetes Dashboard?   That's a high barrier of entry to someone brand new to Kubernetes.  I wanted anyone just starting with Kubernetes to be able to get up and running very quickly while they're learning.

**Comment by attzonko** [comment]
Thanks for the quick response. I did indeed get introduced to this tool as part of a training. It has a very nice visualization of all the different k8s entities. 

It would be awesome if the Dashboard has a nice visual representation of namespaces/deployments/services/nodes/etc.
